services:
  main-db-server:
    image: postgres:17-alpine
    container_name: main-db-server
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=redemonitor
    ports:
      - "5433:5432"
    volumes:
      - postgresql_data:/var/lib/postgresql/data

  rabbitmq-server:
    image: rabbitmq:management
    container_name: rabbitmq-server
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
      - RABBITMQ_DEFAULT_VHOST=/
      - RABBITMQ_NODENAME=rabbit@rabbitmq-server
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/log/rabbitmq
      - rabbitmq_conf:/etc/rabbitmq
    
  mail-server:
    image: axigen/axigen
    container_name: mail-server
    ports:
      - "80:80"
      - "443:443"
      - "993:993"
      - "995:995"
      - "25:25"
      - "465:465"
      - "7000:7000"
      - "9000:9000"
      - "9443:9443"
    volumes:
      - mail_server_data:/axigen/var

  main-api:
    build: ./main-api/
    container_name: main-api
    ports:
      - 8080:8080
    environment:
      - APP_PORT=8080
      - MICROSERVICE_ACCESS_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJjb20ucmVkZW1vbml0b3IiLCJzdWIiOiJtaWNyb3NlcnZpY2UiLCJyb2xlcyI6WyJtaWNyb3NlcnZpY2UiXSwiZXhwIjozOTA5NjgyNzc5fQ.EwZ7nVTGbwUlO8vYpuRifMiZDl4qHm0wUA-bETeZSpY
      - DB_URL=jdbc:postgresql://main-db-server:5432/redemonitor
      - DB_USER=postgres
      - DB_PASS=postgres 
      - RABBITMQ_HOST=rabbitmq-server
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_DISPOSITIVOS_EXCHANGE=dispositivos-exchange
      - RABBITMQ_DISPOSITIVOS_QUEUE1=dispositivos-queue1
      - RABBITMQ_DISPOSITIVOS_QUEUE2=dispositivos-queue2
      - RABBITMQ_DISPOSITIVOS_QUEUE3=dispositivos-queue3
      - RABBITMQ_CONFIGS_EXCHANGE=configs-exchange
      - RABBITMQ_CONFIGS_QUEUE1=configs-queue1
      - RABBITMQ_CONFIGS_QUEUE2=configs-queue2
      - RABBITMQ_CONFIGS_QUEUE3=configs-queue3
      - RABBITMQ_DISPOSITIVOS_STATE_QUEUE=dispositivos-state-queue
      - RABBITMQ_EVENTOS_QUEUE=eventos-queue
      - APP_SERVER_URL=http://main-api:8080
      - JWT_SECRET=949f5f9c8048fa7ff45ffc69e8208a26cd3865e29c65ff720abe330d68e4a572
    depends_on:
      - main-db-server
      - rabbitmq-server

  disp-monitor-api-1:
    build: ./disp-monitor-api/
    container_name: disp-monitor-api-1
    ports:
      - 8081:8081
    environment:
      - APP_PORT=8081
      - RABBITMQ_HOST=rabbitmq-server
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_VIRTUAL_HOST=/
      - RABBITMQ_DISPOSITIVOS_STATE_QUEUE=dispositivos-state-queue
      - RABBITMQ_DISPOSITIVOS_STATE_EXCHANGE=dispositivos-state-exchange
      - RABBITMQ_DISPOSITIVOS_STATE_ROUTING_KEY=dispositivos-state-routing-key
      - RABBITMQ_EVENTOS_QUEUE=eventos-queue
      - RABBITMQ_EVENTOS_EXCHANGE=eventos-exchange
      - RABBITMQ_EVENTOS_ROUTING_KEY=eventos-routing-key
      - RABBITMQ_DISPOSITIVOS_QUEUE=dispositivos-queue1
      - RABBITMQ_CONFIGS_QUEUE=configs-queue1
      - APP_SERVER_URL=http://disp-monitor-api-1:8081
      - JWT_SECRET=949f5f9c8048fa7ff45ffc69e8208a26cd3865e29c65ff720abe330d68e4a572
    depends_on:
      - rabbitmq-server

  disp-monitor-api-2:
    build: ./disp-monitor-api/
    container_name: disp-monitor-api-2
    ports:
      - 8082:8082
    environment:
      - APP_PORT=8082
      - RABBITMQ_HOST=rabbitmq-server
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_VIRTUAL_HOST=/
      - RABBITMQ_DISPOSITIVOS_STATE_QUEUE=dispositivos-state-queue
      - RABBITMQ_DISPOSITIVOS_STATE_EXCHANGE=dispositivos-state-exchange
      - RABBITMQ_DISPOSITIVOS_STATE_ROUTING_KEY=dispositivos-state-routing-key
      - RABBITMQ_EVENTOS_QUEUE=eventos-queue
      - RABBITMQ_EVENTOS_EXCHANGE=eventos-exchange
      - RABBITMQ_EVENTOS_ROUTING_KEY=eventos-routing-key
      - RABBITMQ_DISPOSITIVOS_QUEUE=dispositivos-queue2
      - RABBITMQ_CONFIGS_QUEUE=configs-queue2
      - APP_SERVER_URL=http://disp-monitor-api-2:8082
      - JWT_SECRET=949f5f9c8048fa7ff45ffc69e8208a26cd3865e29c65ff720abe330d68e4a572
    depends_on:
      - rabbitmq-server

  disp-monitor-api-3:
    build: ./disp-monitor-api/
    container_name: disp-monitor-api-3
    ports:
      - 8083:8083
    environment:
      - APP_PORT=8083
      - RABBITMQ_HOST=rabbitmq-server
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=admin
      - RABBITMQ_PASSWORD=admin
      - RABBITMQ_VIRTUAL_HOST=/
      - RABBITMQ_DISPOSITIVOS_STATE_QUEUE=dispositivos-state-queue
      - RABBITMQ_DISPOSITIVOS_STATE_EXCHANGE=dispositivos-state-exchange
      - RABBITMQ_DISPOSITIVOS_STATE_ROUTING_KEY=dispositivos-state-routing-key
      - RABBITMQ_EVENTOS_QUEUE=eventos-queue
      - RABBITMQ_EVENTOS_EXCHANGE=eventos-exchange
      - RABBITMQ_EVENTOS_ROUTING_KEY=eventos-routing-key
      - RABBITMQ_DISPOSITIVOS_QUEUE=dispositivos-queue3
      - RABBITMQ_CONFIGS_QUEUE=configs-queue3
      - APP_SERVER_URL=http://disp-monitor-api-3:8083
      - JWT_SECRET=949f5f9c8048fa7ff45ffc69e8208a26cd3865e29c65ff720abe330d68e4a572
    depends_on:
      - rabbitmq-server

  frontend-app:
    build: ./frontend-app/
    container_name: frontend-app
    environment:
      - VITE_REACT_APP_BASE_API_URL=http://localhost:8080/api/v1
      - VITE_REACT_APP_BASE_WS_URL=ws://localhost:8080/ws/websocket
    ports:
      - 5173:5173

volumes:
  postgresql_data:
    driver: local
  rabbitmq_data:
    driver: local
  rabbitmq_log:
    driver: local
  rabbitmq_conf:
    driver: local
  mail_server_data:
    driver: local
   